[package]
name = "crafting_interpreter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "crafting_interpreter"  # 追加
path = "src/main.rs"           # エントリーポイントとなるファイルを指定

[lib]
name = "crafting_interpreter"
path = "src/lib.rs"

[dependencies]
termcolor = "1.2"