name: Deploy Rust Docs

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust Docs
        run: cargo doc --no-deps

      - name: Setup Git Config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create or Switch to gh-pages
        run: |
          git fetch origin gh-pages || true
          git branch gh-pages origin/gh-pages || git branch gh-pages
          git checkout gh-pages
          rm -rf *
          cp -r target/doc/* .
          touch .nojekyll # 必要に応じてGitHub Pagesの設定ファイル

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Deploy Rust Docs" || echo "No changes to commit"
          git push origin gh-pages --force